# Azure pipeline to build and run daemon tests into Docker image

trigger:
  branches:
    include:
    - '*'

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

pool: Default

steps:
- task: Docker@2
  displayName: Build and run daemon tests
  inputs:
    command: build
    dockerfile: '$(Build.SourcesDirectory)/Dockerfile.daemon_tests'
    tags: |
      $(tag)
